export const users: User[] = [
  {
    id: 0,
    first_name: "Concierge",
    last_name: "Chatbot",
    email: "Concierge@chatbot.com",
    gender: "bot",
    image: "https://xsgames.co/randomusers/avatar.php?g=pixel",
    isPinned: true,
    recentMessage: null,
    messages: [],
    industry: null,
    location: null,
  },
  {
    id: 1,
    first_name: "Ingeberg",
    last_name: "Zanioletti",
    email: "izanioletti0@elegantthemes.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/10.jpg",
    isPinned: true,
    recentMessage: {
      message:
        "Absolutely! I'll prepare the detailed estimate and include any additional services that might enhance your travel experience. If you have any specific requests or questions, don't hesitate to ask. Excited to help plan your memorable trip to India!",
      time: "2024-02-02T13:15:12.391Z",
      read: false,
      senderId: "1",
    },
    messages: [
      {
        message:
          "Hello Ingeberg! Yes, I'm interested in exploring Travel Planning Services for my upcoming trip to India. Could you provide more details about the services you offer?",
        time: "2024-02-02T13:00:12.391Z",
        read: true,
        senderId: "-1",
      },
      {
        message:
          "Of course! Our Travel Planning Services include personalized itineraries, accommodation recommendations, and transportation arrangements. Are there specific aspects of your trip you'd like assistance with?",
        time: "2024-02-02T13:15:12.391Z",
        read: true,
        senderId: "1",
      },
      {
        message:
          "That sounds promising! I'm particularly interested in knowing about the pricing for the personalized itineraries. Can you provide some details on the cost?",
        time: "2024-02-02T13:30:12.391Z",
        read: true,
        senderId: "-1",
      },
      {
        message:
          "Certainly! The pricing for our personalized itineraries varies based on the duration of your trip, the number of cities you plan to visit, and any specific activities or attractions you'd like to include. Do you have a rough idea of your travel dates and preferences?",
        time: "2024-02-02T13:45:12.391Z",
        read: true,
        senderId: "1",
      },
      {
        message:
          "I'll be in India for two weeks, and I'm interested in exploring Delhi, Jaipur, and Mumbai. Could you provide an estimate for a personalized itinerary covering these cities?",
        time: "2024-02-02T14:00:12.391Z",
        read: true,
        senderId: "-1",
      },
      {
        message:
          "Absolutely! For a two-week itinerary covering Delhi, Jaipur, and Mumbai, we can tailor a package that includes accommodation, transportation, and guided tours. I'll provide you with a detailed estimate shortly. Are there any specific preferences or activities you'd like to emphasize?",
        time: "2024-02-02T13:15:12.391Z",
        read: true,
        senderId: "1",
      },
      {
        message:
          "I'm open to cultural experiences, historical sites, and trying local cuisines. Any recommendations or inclusions based on that?",
        time: "2024-02-02T13:30:12.391Z",
        read: true,
        senderId: "-1",
      },
      {
        message:
          "Wonderful choices! We can incorporate visits to historical landmarks, cultural events, and renowned local eateries. I'll factor in these preferences while finalizing the itinerary and provide you with a comprehensive breakdown of the costs. Does that sound good to you?",
        time: "2024-02-02T13:45:12.391Z",
        read: true,
        senderId: "1",
      },
      {
        message:
          "Perfect! I appreciate your assistance. Looking forward to receiving the detailed estimate. Also, if there are any additional services available, feel free to let me know!",
        time: "2024-02-02T13:00:12.391Z",
        read: true,
        senderId: "-1",
      },
      {
        message:
          "Absolutely! I'll prepare the detailed estimate and include any additional services that might enhance your travel experience. If you have any specific requests or questions, don't hesitate to ask. Excited to help plan your memorable trip to India!",
        time: "2024-02-02T13:15:12.391Z",
        read: false,
        senderId: "1",
      },
    ],
    industry: "Travel Planning Services",
    location: "India",
  },
  {
    id: 2,
    first_name: "Valma",
    last_name: "Chishull",
    email: "vchishull1@independent.co.uk",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/11.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Dining Reservations",
    location: "Singapore",
  },
  {
    id: 3,
    first_name: "Arleen",
    last_name: "Bailes",
    email: "abailes2@washingtonpost.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/12.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Event Ticketing",
    location: "India",
  },
  {
    id: 4,
    first_name: "Byran",
    last_name: "Tankus",
    email: "btankus3@sbwire.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/12.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Wellness and Spa Services",
    location: "Singapore",
  },
  {
    id: 5,
    first_name: "Silvano",
    last_name: "Tabert",
    email: "stabert4@noaa.gov",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/13.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Home Services",
    location: "India",
  },
  {
    id: 6,
    first_name: "Courtney",
    last_name: "Jillard",
    email: "cjillard5@wordpress.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/14.jpg",
    isPinned: true,
    recentMessage: null,
    messages: [],
    industry: "Electronics",
    location: "Singapore",
  },
  {
    id: 7,
    first_name: "Godiva",
    last_name: "Ruppert",
    email: "gruppert6@sogou.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/14.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Fashion and Accessories",
    location: "India",
  },
  {
    id: 8,
    first_name: "Collin",
    last_name: "Donizeau",
    email: "cdonizeau7@dyndns.org",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/15.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Home and Kitchen Appliances",
    location: "Singapore",
  },
  {
    id: 9,
    first_name: "Seth",
    last_name: "Brocklehurst",
    email: "sbrocklehurst8@theguardian.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/16.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Beauty and Personal Care Products",
    location: "India",
  },
  {
    id: 10,
    first_name: "Araldo",
    last_name: "Mendel",
    email: "amendel9@nih.gov",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/17.jpg",
    isPinned: false,
    recentMessage: {
      message: "No specific preference. Just looking for some exciting reads. Feel free to share your recommendations, and I'll take it from there!",
      time: "2024-02-01T16:45:00Z",
      read: true,
      senderId: "-1",
    },
    messages: [{
      message: "Hello Araldo! I'm currently on the lookout for some intriguing books in Singapore. Do you have any recommendations or a list of featured books in your collection?",
      time: "2024-02-01T15:30:00Z",
      read: true,
      senderId: "-1",
    },
    {
      message: "Absolutely! We have a diverse collection of books ranging from bestsellers to classics and niche genres. Whether you're into fiction, non-fiction, or specific themes, we've got something for every reader. Any particular genre or theme you're interested in?",
      time: "2024-02-01T16:00:00Z",
      read: true,
      senderId: "10",
    },
    {
      message: "That sounds fantastic! I'm particularly interested in fiction, especially mystery and adventure genres. Do you have any recommendations in that category?",
      time: "2024-02-01T16:15:00Z",
      read: true,
      senderId: "-1",
    },
    {
      message: "Certainly! We have some captivating mystery and adventure novels in our collection. I'll provide you with a list of recommended books shortly. Is there a specific author or style you prefer?",
      time: "2024-02-01T16:30:00Z",
      read: true,
      senderId: "10",
    },
    {
      message: "No specific preference. Just looking for some exciting reads. Feel free to share your recommendations, and I'll take it from there!",
      time: "2024-02-01T16:45:00Z",
      read: true,
      senderId: "-1",
    },],
    industry: "Books and Stationery",
    location: "Singapore",
  },
  {
    id: 11,
    first_name: "Adara",
    last_name: "Mertel",
    email: "amertel10@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/15.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Travel Planning Services",
    location: "Singapore",
  },
  {
    id: 12,
    first_name: "Osman",
    last_name: "Folley",
    email: "ofolley11@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/18.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Dining Reservations",
    location: "India",
  },
  {
    id: 13,
    first_name: "Ismail",
    last_name: "Clegg",
    email: "iclegg12@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/19.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Event Ticketing",
    location: "Singapore",
  },
  {
    id: 14,
    first_name: "Soraya",
    last_name: "Coulson",
    email: "scoulson13@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/16.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Wellness and Spa Services",
    location: "India",
  },
  {
    id: 15,
    first_name: "Elena",
    last_name: "Burrell",
    email: "eburrell14@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/17.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Home Services",
    location: "Singapore",
  },
  {
    id: 16,
    first_name: "Benedict",
    last_name: "Hollingworth",
    email: "bhollingworth15@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/20.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Electronics",
    location: "India",
  },
  {
    id: 17,
    first_name: "Imelda",
    last_name: "Chapman",
    email: "ichapman16@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/18.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Fashion and Accessories",
    location: "Singapore",
  },
  {
    id: 18,
    first_name: "Rafferty",
    last_name: "Rylands",
    email: "rrylands17@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/21.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Home and Kitchen Appliances",
    location: "India",
  },
  {
    id: 19,
    first_name: "Jemima",
    last_name: "Hargreaves",
    email: "jhargreaves18@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/19.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Beauty and Personal Care Products",
    location: "Singapore",
  },
  {
    id: 20,
    first_name: "Zara",
    last_name: "Moss",
    email: "zmoss19@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/20.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Books and Stationery",
    location: "India",
  },
  {
    id: 21,
    first_name: "Malcolm",
    last_name: "Carver",
    email: "mcarver20@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/22.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Travel Planning Services",
    location: "Singapore",
  },
  {
    id: 22,
    first_name: "Valentina",
    last_name: "Puckett",
    email: "vpuckett21@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/21.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Dining Reservations",
    location: "India",
  },
  {
    id: 23,
    first_name: "Ishmael",
    last_name: "Huxley",
    email: "ihuxley22@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/23.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Event Ticketing",
    location: "Singapore",
  },
  {
    id: 24,
    first_name: "Roslyn",
    last_name: "Riggs",
    email: "rriggs23@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/22.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Wellness and Spa Services",
    location: "India",
  },
  {
    id: 25,
    first_name: "Cassius",
    last_name: "Wilkinson",
    email: "cwilkinson24@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/24.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Home Services",
    location: "Singapore",
  },
  {
    id: 26,
    first_name: "Francesca",
    last_name: "Hurley",
    email: "fhurley25@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/23.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Electronics",
    location: "India",
  },
  {
    id: 27,
    first_name: "Rupert",
    last_name: "Parrish",
    email: "rparrish26@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/25.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Fashion and Accessories",
    location: "Singapore",
  },
  {
    id: 28,
    first_name: "Dulcie",
    last_name: "Swan",
    email: "dswan27@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/24.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Home and Kitchen Appliances",
    location: "India",
  },
  {
    id: 29,
    first_name: "Amari",
    last_name: "Thorpe",
    email: "athorpe28@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/26.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Beauty and Personal Care Products",
    location: "Singapore",
  },
  {
    id: 30,
    first_name: "Elouise",
    last_name: "Higgins",
    email: "ehiggins29@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/25.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Books and Stationery",
    location: "India",
  },
  {
    id: 31,
    first_name: "Keaton",
    last_name: "Hawkins",
    email: "khawkins30@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/27.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Travel Planning Services",
    location: "Singapore",
  },
  {
    id: 32,
    first_name: "Marleigh",
    last_name: "Cortes",
    email: "mcortes31@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/26.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Dining Reservations",
    location: "India",
  },
  {
    id: 33,
    first_name: "Zak",
    last_name: "Heath",
    email: "zheath32@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/28.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Event Ticketing",
    location: "Singapore",
  },
  {
    id: 34,
    first_name: "Esmee",
    last_name: "Pearce",
    email: "epearce33@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/27.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Wellness and Spa Services",
    location: "India",
  },
  {
    id: 35,
    first_name: "Eli",
    last_name: "Mcbride",
    email: "emcbride34@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/29.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Home Services",
    location: "India",
  },
  {
    id: 36,
    first_name: "Alena",
    last_name: "Reeves",
    email: "areeves35@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/28.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Electronics",
    location: "Singapore",
  },
  {
    id: 37,
    first_name: "Koen",
    last_name: "Tate",
    email: "ktate36@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/30.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Fashion and Accessories",
    location: "India",
  },
  {
    id: 38,
    first_name: "Kiera",
    last_name: "Puckett",
    email: "kpuckett37@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/29.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Home and Kitchen Appliances",
    location: "Singapore",
  },
  {
    id: 39,
    first_name: "Amari",
    last_name: "Goodman",
    email: "agoodman38@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/31.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Beauty and Personal Care Products",
    location: "India",
  },
  {
    id: 40,
    first_name: "Zaina",
    last_name: "Archer",
    email: "zarcher39@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/30.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Books and Stationery",
    location: "Singapore",
  },
  {
    id: 41,
    first_name: "Nehemiah",
    last_name: "Barker",
    email: "nbarker40@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/32.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Travel Planning Services",
    location: "India",
  },
  {
    id: 42,
    first_name: "Anika",
    last_name: "Wheeler",
    email: "awheeler41@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/31.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Dining Reservations",
    location: "Singapore",
  },
  {
    id: 43,
    first_name: "Jaxon",
    last_name: "Ashley",
    email: "jashley42@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/33.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Event Ticketing",
    location: "India",
  },
  {
    id: 44,
    first_name: "Kaisha",
    last_name: "Cummings",
    email: "kcummings43@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/32.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Wellness and Spa Services",
    location: "Singapore",
  },
  {
    id: 45,
    first_name: "Tate",
    last_name: "Steele",
    email: "tsteele44@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/34.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Home Services",
    location: "India",
  },
  {
    id: 46,
    first_name: "Aiysha",
    last_name: "Bryan",
    email: "abryan45@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/33.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Electronics",
    location: "Singapore",
  },
  {
    id: 47,
    first_name: "Khalil",
    last_name: "Weaver",
    email: "kweaver46@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/35.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Fashion and Accessories",
    location: "India",
  },
  {
    id: 48,
    first_name: "Rosalyn",
    last_name: "Lowe",
    email: "rlowe47@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/34.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Home and Kitchen Appliances",
    location: "Singapore",
  },
  {
    id: 49,
    first_name: "Kellan",
    last_name: "Webb",
    email: "kwebb48@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/36.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Beauty and Personal Care Products",
    location: "India",
  },
  {
    id: 50,
    first_name: "Amina",
    last_name: "Mclaughlin",
    email: "amclaughlin49@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/35.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Books and Stationery",
    location: "Singapore",
  },
  {
    id: 51,
    first_name: "Mikolaj",
    last_name: "Bond",
    email: "mbond50@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/37.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Travel Planning Services",
    location: "India",
  },
  {
    id: 52,
    first_name: "Inaya",
    last_name: "Riggs",
    email: "iriggs51@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/36.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Dining Reservations",
    location: "Singapore",
  },
  {
    id: 53,
    first_name: "Nevin",
    last_name: "Dillon",
    email: "ndillon52@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/38.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Event Ticketing",
    location: "India",
  },
  {
    id: 54,
    first_name: "Lillia",
    last_name: "Hodges",
    email: "lhodges53@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/37.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Wellness and Spa Services",
    location: "Singapore",
  },
  {
    id: 55,
    first_name: "Rajveer",
    last_name: "Peters",
    email: "rpeters54@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/39.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Home Services",
    location: "India",
  },
  {
    id: 56,
    first_name: "Leyla",
    last_name: "Wright",
    email: "lwright55@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/38.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Electronics",
    location: "Singapore",
  },
  {
    id: 57,
    first_name: "Casper",
    last_name: "Pugh",
    email: "cpugh56@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/40.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Fashion and Accessories",
    location: "India",
  },
  {
    id: 58,
    first_name: "Kendra",
    last_name: "Baxter",
    email: "kbaxter57@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/39.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Home and Kitchen Appliances",
    location: "Singapore",
  },
  {
    id: 59,
    first_name: "Keagan",
    last_name: "Glover",
    email: "kglover58@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/41.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Beauty and Personal Care Products",
    location: "India",
  },
  {
    id: 60,
    first_name: "Janae",
    last_name: "Lowe",
    email: "jlowe59@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/40.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Books and Stationery",
    location: "Singapore",
  },
  {
    id: 61,
    first_name: "Jovan",
    last_name: "Chapman",
    email: "jchapman60@example.com",
    gender: "Male",
    image: "https://xsgames.co/randomusers/assets/avatars/male/42.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Travel Planning Services",
    location: "India",
  },
  {
    id: 62,
    first_name: "Miah",
    last_name: "Riley",
    email: "mriley61@example.com",
    gender: "Female",
    image: "https://xsgames.co/randomusers/assets/avatars/female/41.jpg",
    isPinned: false,
    recentMessage: null,
    messages: [],
    industry: "Dining Reservations",
    location: "Singapore",
  },
];

export interface User {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  gender: string;
  image: string;
  isPinned: boolean;
  recentMessage: Message | null;
  messages: Message[];
  industry: string|null;
  location: string|null;
}
export interface Message{
  message:string,
  time:string,
  read:boolean,
  senderId:string
}